image: maven:3.3.9-jdk-8

stages:
  - validate
  - test
  - build
  - artifact
  - deploy

validate:
  stage: validate
  script:
    - mvn validate

unit-test:
  stage: test
  script:
    - mvn test

building:
  stage: build
  script:
    - mvn package

deploy:
  stage: deploy
  script:
    - git remote add heroku https://paulushc:$HEROKU_KEY@git.heroku.com/ufscar-devops-paulushc2.git
    - git push heroku master
  environment:
    name: producao
    url: https://ufscar-devops-paulushc2.herokuapps.com
  only:
    - master
  when: manual