image: maven:3.3.9-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

cache:
  paths:
    - .m2/repository

stages:
  - validate
  - test
  - build
  - artifact
  - deploy

deploy:
  stage: deploy
  script:
    - git show-ref
    - git remote add heroku https://paulushc:$HEROKU_KEY@git.heroku.com/ufscar-devops-paulushc2.git
    - git push heroku HEAD:master -f
  environment:
    name: producao
    url: https://ufscar-devops-paulushc2.herokuapp.com
  only:
    - master
  when: manual